### ISSUE TITLE
Failing to load CSS for my site

### ISSUE THREAD

**Issue by Anthonyphilftwplz** [poole/hyde#254] opened 2019-12-10 22:44 UTC
I am failing to load the CSS for my site:

Getting this error message
Failed to load resource: the server responded with a status  styles.css:1  404 ()

Here is my link on html:  link rel="stylesheet" href="css/styles.css">

**Comment by Anthonyphilftwplz** [comment] 2019-12-10 22:45
<link rel="stylesheet" href="css/styles.css">

**Comment by akashpalrecha** [comment] 2020-01-30 08:54
Check out #213. It should solve your issue.

**Comment by mdo** [comment] 2020-04-04 06:10
Duplicate of #206

**Closed as completed by mdo** 2020-04-04 06:10 UTC
