### ISSUE TITLE
Increase width of content in hyde theme

### ISSUE THREAD

**Issue by OneRaynyDay** [poole/hyde#240] opened 2019-02-17 22:02 UTC
Hi, first thanks so much for creating this framework! I've been using it for my blog for the past few years: https://oneraynyday.github.io/

Lately I've been writing some math-related blogs and the restricted width of the framework is starting to bother me a little bit (as shown below):

![image](https://user-images.githubusercontent.com/7191678/52919928-5acaee80-32bc-11e9-85a3-9621fd0d3e00.png)

In most uses this width is fine, but for math it makes the LaTeX equations cluster up and look very intimidating, which is not what I am trying to do.

I'm by no means proficient at CSS and I couldn't find any documentation regarding Hyde to adjust the width of the container. I was hoping posting here would help.

Any tips would be appreciated!

**Comment by brightertiger** [comment] 2019-04-02 04:23
In the file public/css/hyde.css - if you change the width option then it can get you the desired result.

.sidebar {
  text-align: center;
  padding: 2rem 1rem;
  color: rgba(255,255,255,.5);
  background-color: #202020;
}
@media (min-width: 48em) {
  .sidebar {
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    **width: 18rem;**
    text-align: left;
  }
}

**Comment by mdo** [comment] 2020-04-04 06:13
Duplicate of #195.

**Closed as completed by mdo** 2020-04-04 06:13 UTC
